from turtle import *
up()
goto(-200,200)
down()
begin_fill()
fillcolor("red")
pencolor("red")
for i in range(2):
    forward(280)
    right(90)
    forward(200)
    right(90)
end_fill()
up()
goto(-170,145)
down()
begin_fill()
fillcolor("yellow")
pencolor("yellow")
for x in range(5):
    forward(50)
    right(144)
end_fill()
up()
goto(-100,180)
down()
begin_fill()
fillcolor("yellow")
pencolor("yellow")
seth(-27)
for x in range(5):
    forward(20)
    right(144)
end_fill()
up()
goto(-70,160)
down()
begin_fill()
fillcolor("yellow")
pencolor("yellow")
seth(-40)
for x in range(5):
    forward(20)
    right(144)
end_fill()
up()
goto(-70,120)
down()
begin_fill()
fillcolor("yellow")
pencolor("yellow")
seth(0)
for x in range(5):
    forward(20)
    right(144)
end_fill()
up()
goto(-100,100)
down()
begin_fill()
fillcolor("yellow")
pencolor("yellow")
seth(-27)
for x in range(5):
    forward(20)
    right(144)
end_fill() 

